# Generated by Django 3.2.7 on 2022-05-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220426_1011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='category',
            new_name='name',
        ),
        migrations.AddField(
            model_name='category',
            name='cat_img',
            field=models.ImageField(default='images/logo.png', upload_to='images/'),
        ),
    ]
