# Generated by Django 3.2.7 on 2022-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220424_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='images/user/account-avatar-profile.png', upload_to='images/user/'),
        ),
    ]
